### ISSUE TITLE
missing or incorrect file name

### ISSUE THREAD

**Issue by msrosenberg** [SchwartzLabURI/SISRS#39]
I'm trying to get sisrs running on our system and when I tried to analyze the test data set I get the following error:

```
Traceback (most recent call last):
  File "/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs.py", line 6, in <module>
    from existingRun import *
  File "/lustre/home/msrosenberg/soft/SISRS/scripts/existingRun.py", line 25, in <module>
    from sisrs_06_run_sisrs import *
ModuleNotFoundError: No module named 'sisrs_06_run_sisrs'
```

There is no module named sisrs_06_run_sisrs.py in the repository. I note that this file name is referenced in at least two modules and in the tutorial as well. There are four files which start with sisrs_06... but none of them have that name.

**Comment by msrosenberg** [comment]
I did some more digging in the github history. The file was changed/split/removed in between version 2.0 and 2.2, but somehow the other scripts were not updated to reflect this change. As it stands, the scripts cannot work with the current release.

**Comment by rachelss** [comment]
My apologies. The SISRS steps should be run sequentially. 
See https://schwartzlaburi.github.io/SISRS_CURE/book/phylogenetic-markers.html

The sisrs.py file has been deleted and the readme has been updated with this link.

**Comment by msrosenberg** [comment]
So I'm running your rest data, step by step and it seems to be working so far (I'm up through step 6; I should note that the output suggested in your tutorial for step 6b is incorrect...that script does not produce files with the species names ending in .fa, rather every folder ends up with a contigs.fa file). 

I'm also running it on my own data set (only six species, but larger input files), a few steps behind. When I hit step 3 on my data set, it runs without any obvious errors, but it only appears to be subsetting 3 of the 6 species for some reason. I've run it twice with different genome sizes as inputs and it did the same thing both times. I assume all 6 should appear in the output?

The slurm output only says the following:

```
['../fiddler_output/Reads/TrimReads/alcocki', '../fiddler_output/Reads/TrimReads/annulipes', '../fiddler_output/Reads/TrimReads/ceratophthalmus', '../fiddler_output/Reads/TrimReads/iranica', '../fiddler_output/Reads/TrimReads/rotundata', '../fiddler_output/Reads/TrimReads/sindensis']
Based on a genome size estimate of 1000000000 bp, and with 6 species, the requested subset depth is 1666666666 bp per species
```

while the slurm "error" has this:

```
/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append((pd.DataFrame(list_of_tuples, columns = ['Taxon','Dataset', 'Basecount'])))
/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append((pd.DataFrame(list_of_tuples, columns = ['Taxon','Dataset', 'Basecount'])))
/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append((pd.DataFrame(list_of_tuples, columns = ['Taxon','Dataset', 'Basecount'])))
/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append((pd.DataFrame(list_of_tuples, columns = ['Taxon','Dataset', 'Basecount'])))
/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append((pd.DataFrame(list_of_tuples, columns = ['Taxon','Dataset', 'Basecount'])))
/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append((pd.DataFrame(list_of_tuples, columns = ['Taxon','Dataset', 'Basecount'])))
java -ea -Xmx300m -Xms300m -cp /lustre/home/msrosenberg/bin/bbmap/current/ jgi.ReformatReads in=../fiddler_output/Reads/TrimReads/ceratophthalmus/ceratophthalmus_Trim_1.fastq.gz in2=../fiddler_output/Reads/TrimReads/ceratophthalmus/ceratophthalmus_Trim_2.fastq.gz out=../fiddler_output/Reads/SubsetReads/ceratophthalmus_GenomeReads_1.fastq.gz out2=../fiddler_output/Reads/SubsetReads/ceratophthalmus_GenomeReads_2.fastq.gz samplebasestarget=1666666666 ow=t &> ../fiddler_output/Reads/TrimReads/subsetOutput/out_ceratophthalmus_Trim
java -ea -Xmx300m -Xms300m -cp /lustre/home/msrosenberg/bin/bbmap/current/ jgi.ReformatReads in=../fiddler_output/Reads/TrimReads/iranica/iranica_Trim_1.fastq.gz in2=../fiddler_output/Reads/TrimReads/iranica/iranica_Trim_2.fastq.gz out=../fiddler_output/Reads/SubsetReads/iranica_GenomeReads_1.fastq.gz out2=../fiddler_output/Reads/SubsetReads/iranica_GenomeReads_2.fastq.gz samplebasestarget=1666666666 ow=t &> ../fiddler_output/Reads/TrimReads/subsetOutput/out_iranica_Trim
java -ea -Xmx300m -Xms300m -cp /lustre/home/msrosenberg/bin/bbmap/current/ jgi.ReformatReads in=../fiddler_output/Reads/TrimReads/rotundata/rotundata_Trim_1.fastq.gz in2=../fiddler_output/Reads/TrimReads/rotundata/rotundata_Trim_2.fastq.gz out=../fiddler_output/Reads/SubsetReads/rotundata_GenomeReads_1.fastq.gz out2=../fiddler_output/Reads/SubsetReads/rotundata_GenomeReads_2.fastq.gz samplebasestarget=1666666666 ow=t &> ../fiddler_output/Reads/TrimReads/subsetOutput/out_rotundata_Trim
```

Of particular importance, note that the java command is only being run 3 times rather than 6.

**Comment by rachelss** [comment]
All taxa should have subsets of data. I am rewriting some scripts to output information for troubleshooting since the reason for not all species having subsets isn't clear.

**Comment by rachelss** [comment]
The expected subsampling scheme is written to the slurm output as well as a csv in the subset folder. Let me know if the files you expect to subset match the files in the printed dataframe.

**Comment by msrosenberg** [comment]
I'm now getting a new error without it finishing.

```
  File "/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py", line 309, in <module>
    data_info_df = checkCoverage(trim_read_dir,data_info_df,subsetDepth,subset_output_dir)
  File "/lustre/home/msrosenberg/soft/SISRS/scripts/sisrs_03_read_subsetter.py", line 215, in checkCoverage
    per_dataset = subsetDepth/dataset_count #Calculate bases needed per sample if evenly distributed
TypeError: unsupported operand type(s) for /: 'list' and 'int'
```

I didn't try to follow the entire logic of the code, but it does look to me like subsetDepth is being created as a list on line 74 of sisrs_03_read_subsetter.py

**Comment by rachelss** [comment]
That does seem to be the problem. I fixed it. Try again?

**Comment by msrosenberg** [comment]
It now works as expected. All six species are present in the subsetting folder. Thanks.

On to step 4...
